# Generated by Django 4.2.6 on 2023-11-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0002_alter_services_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
