# Generated by Django 4.2.6 on 2023-11-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0003_alter_places_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='OperatingHours',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
