# Generated by Django 4.2.6 on 2023-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0004_alter_places_operatinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='OperatingHours',
            field=models.IntegerField(blank=True),
        ),
    ]
