# Generated by Django 4.2.6 on 2023-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0005_alter_places_operatinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('DistanceFromHotel', models.IntegerField(blank=True)),
                ('TypeofAttraction', models.CharField(blank=True, choices=[('historical sites', 'historical sites'), ('natural landmarks', 'natural landmarks'), ('museums', 'museums'), ('recreational activities', 'recreational activities')], max_length=50)),
                ('OperatingHours', models.IntegerField(blank=True)),
                ('LocalDiningPrivision', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'db_table': 'ProvPlace_table',
            },
        ),
    ]
