# Generated by Django 4.2.6 on 2023-11-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0006_provplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_ref_id',
            field=models.CharField(default='REF123', max_length=10),
            preserve_default=False,
        ),
    ]
