# Generated by Django 4.2.6 on 2023-11-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0008_services_hotelrefid'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='EnterRequiredUsername',
            field=models.CharField(default='james_2110', max_length=30),
            preserve_default=False,
        ),
    ]
