# Generated by Django 4.2.6 on 2023-11-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0010_register_enterpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ConfirmPassword',
            field=models.CharField(default='james@2365', max_length=30),
            preserve_default=False,
        ),
    ]
