# Generated by Django 4.2.6 on 2023-11-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0011_register_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
