# Generated by Django 4.2.6 on 2023-11-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0014_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
