# Generated by Django 4.2.6 on 2023-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0015_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='NameofHotel',
            field=models.CharField(default='Andhra Pradesh', max_length=20),
            preserve_default=False,
        ),
    ]
