# Generated by Django 4.2.6 on 2023-11-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0017_services_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='NameofHotel',
        ),
    ]
