# Generated by Django 4.2.6 on 2023-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0019_services_nameofhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='State',
            field=models.CharField(default='Andhra Pradesh', max_length=20),
            preserve_default=False,
        ),
    ]
