# Generated by Django 4.2.6 on 2023-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0020_services_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
