# Generated by Django 4.2.6 on 2023-11-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0021_alter_services_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
