# Generated by Django 4.2.6 on 2023-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerapp', '0022_alter_services_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provservices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NameofHotel', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('hotelRefId', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('AccomodationType', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suites', 'Suites')], max_length=50)),
                ('Amenities', models.CharField(max_length=80)),
                ('RoomNo', models.IntegerField()),
                ('RoomSize', models.CharField(max_length=50)),
                ('RoomType', models.CharField(max_length=60)),
                ('CostPerNight', models.IntegerField()),
                ('CheckInandCheckOutPolicies', models.CharField(blank=True, max_length=100)),
                ('Diningtype', models.CharField(choices=[('FineDine', 'FineDine'), ('CasualDine', 'CasualDine'), ('Buffet', 'Buffet'), ('Bestro', 'Bestro')], max_length=60)),
                ('diningTimings', models.CharField(max_length=60)),
                ('BarandBeverageservice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('privateDining', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
                ('LiveEntertainment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=60)),
            ],
            options={
                'db_table': 'Provservice_table',
            },
        ),
    ]
