# Generated by Django 4.2.6 on 2023-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('cleanliness', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('comfort', models.CharField(max_length=100)),
                ('amenities', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': 'Feedback_table',
            },
        ),
    ]
