# Generated by Django 4.2.6 on 2023-10-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Touristadmin',
            new_name='Admin',
        ),
    ]
